import { StyleSheet, Platform } from 'react-native';
import { colors, getElevationStyle } from './colors';

export const foodScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background.primary,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: Platform.select({
      ios: 100, // Extra padding for iOS tab bar
      android: 80,
      default: 80,
    }),
  },
  header: {
    backgroundColor: colors.surface.level1,
    padding: 20,
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: colors.primary[500],
    ...colors.shadows.small,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 5,
    color: colors.text.primary,
  },
  date: {
    fontSize: 16,
    color: colors.text.secondary,
    marginBottom: 10,
  },
  calories: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.primary[500],
  },
  protein: {
    fontSize: 16,
    fontWeight: '500',
    color: colors.text.secondary,
  },
  measurementGuide: {
    ...getElevationStyle(2),
    margin: 15,
    padding: 15,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.primary[500],
  },
  guideTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 10,
    textAlign: 'center',
    color: colors.text.primary,
  },
  guideRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  guideItem: {
    fontSize: 12,
    color: colors.text.secondary,
  },
  mealsContainer: {
    padding: 15,
  },
  mealSection: {
    ...getElevationStyle(1),
    marginBottom: 15,
    borderRadius: 12,
    padding: 15,
    borderWidth: 1,
    borderColor: colors.border.secondary,
  },
  mealHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  mealTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.text.primary,
  },
  mealCalories: {
    fontSize: 16,
    color: colors.primary[500],
    fontWeight: '500',
  },
  mealProtein: {
    fontSize: 14,
    color: colors.text.secondary,
    fontWeight: '400',
  },
  mealNutrition: {
    flexDirection: 'column',
    alignItems: 'flex-end',
  },
  noEntries: {
    fontSize: 14,
    color: '#a0a0a0',
    fontStyle: 'italic',
    marginBottom: 10,
  },
  foodEntry: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#6a6a6a',
  },
  foodEntryLeft: {
    flex: 1,
  },
  foodEntryActions: {
    flexDirection: 'row',
    gap: 8,
  },
  editButton: {
    backgroundColor: '#a82828',
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 4,
  },
  editButtonText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '600',
  },
  deleteButton: {
    backgroundColor: '#ff3b30',
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 4,
  },
  deleteButtonText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '600',
  },
  foodName: {
    fontSize: 16,
    fontWeight: '500',
    marginBottom: 2,
    color: '#ffffff',
  },
  foodDetails: {
    fontSize: 12,
    color: '#c5c5c5',
  },
  addButton: {
    backgroundColor: colors.primary[500],
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 10,
    ...colors.shadows.button,
  },
  addButtonText: {
    color: colors.text.primary,
    fontWeight: '600',
    fontSize: 16,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalScrollContainer: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 20,
    paddingBottom: 150, // Extra bottom padding for keyboard during custom input
  },
  modalScrollContainerCustom: {
    flexGrow: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingTop: 50,
    paddingBottom: 200, // Extra bottom padding for keyboard during custom input
    paddingHorizontal: 10,
  },
  modalContent: {
    backgroundColor: colors.surface.level2,
    margin: 20,
    padding: 20,
    borderRadius: 12,
    width: '90%',
    maxWidth: 400,
    minHeight: 300,
    ...colors.shadows.large,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 20,
    textAlign: 'center',
    color: colors.text.primary,
  },
  inputGroup: {
    marginBottom: 15,
  },
  inputRow: {
    flexDirection: 'row',
    gap: 15,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 5,
    color: '#ffffff',
  },
  modalInput: {
    borderWidth: 1,
    borderColor: '#6a6a6a',
    borderRadius: 5,
    padding: 10,
    fontSize: 16,
    backgroundColor: colors.surface.level1,
    color: colors.text.primary,
    minHeight: 40,
  },
  unitSelector: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  unitButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#6a6a6a',
    borderRadius: 5,
    backgroundColor: '#4a4a4a',
  },
  selectedUnit: {
    backgroundColor: '#a82828',
    borderColor: '#007AFF',
  },
  unitText: {
    fontSize: 14,
    color: '#ffffff',
  },
  selectedUnitText: {
    color: '#fff',
    fontWeight: '600',
  },
  measurementHint: {
    backgroundColor: '#4a4a4a',
    padding: 12,
    borderRadius: 8,
    marginBottom: 15,
  },
  hintTitle: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 6,
    color: '#ffffff',
  },
  hintText: {
    fontSize: 12,
    color: '#c5c5c5',
    marginBottom: 2,
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 10,
  },
  modalButton: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 5,
    minWidth: 100,
    alignItems: 'center',
  },
  cancelButton: {
    backgroundColor: '#4a4a4a',
  },
  cancelButtonText: {
    color: '#c5c5c5',
    fontWeight: '600',
  },
  saveButton: {
    backgroundColor: '#a82828',
  },
  saveButtonText: {
    color: '#fff',
    fontWeight: '600',
  },
  searchResults: {
    maxHeight: 150,
    borderWidth: 1,
    borderColor: '#6a6a6a',
    borderRadius: 5,
    marginBottom: 15,
  },
  foodResult: {
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#6a6a6a',
  },
  foodResultName: {
    fontSize: 16,
    fontWeight: '500',
  },
  foodResultCategory: {
    fontSize: 12,
    color: '#c5c5c5',
    marginTop: 2,
  },
  selectedFoodInfo: {
    backgroundColor: '#4a4a4a',
    padding: 12,
    borderRadius: 8,
    marginBottom: 15,
  },
  selectedFoodName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#a82828',
  },
  selectedFoodDetails: {
    fontSize: 12,
    color: '#c5c5c5',
    marginTop: 2,
  },
  nutritionInfo: {
    backgroundColor: '#4a4a4a',
    padding: 12,
    borderRadius: 8,
    marginBottom: 15,
  },
  nutritionTitle: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 8,
    color: '#ffffff',
  },
  nutritionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  nutritionItem: {
    fontSize: 12,
    color: '#c5c5c5',
    flex: 1,
  },
  disabledButton: {
    backgroundColor: '#555555',
  },
  disabledText: {
    color: '#a0a0a0',
  },
  deleteConfirmModal: {
    backgroundColor: '#3c3c3c',
    margin: 20,
    padding: 20,
    borderRadius: 10,
    width: '80%',
  },
  deleteConfirmTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 15,
    textAlign: 'center',
    color: '#ff3b30',
  },
  deleteConfirmText: {
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 20,
    color: '#ffffff',
    lineHeight: 22,
  },
  deleteConfirmButtons: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  confirmDeleteButton: {
    backgroundColor: '#ff3b30',
  },
  confirmDeleteText: {
    color: '#fff',
    fontWeight: '600',
  },
  apiWarning: {
    backgroundColor: '#8b4513',
    padding: 12,
    borderRadius: 8,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: '#a82828',
  },
  apiWarningText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 4,
  },
  apiWarningSubtext: {
    color: '#e0e0e0',
    fontSize: 12,
  },
  searchingText: {
    color: '#a82828',
    fontSize: 12,
    fontStyle: 'italic',
    marginTop: 5,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  calendarButton: {
    backgroundColor: '#a82828',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 6,
  },
  calendarButtonText: {
    fontSize: 20,
  },
  dateButton: {
    paddingVertical: 5,
    paddingHorizontal: 10,
    backgroundColor: '#4a4a4a',
    borderRadius: 6,
    marginBottom: 8,
  },
  inputMethodSection: {
    marginBottom: 20,
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#6a6a6a',
  },
  inputMethodTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 15,
    textAlign: 'center',
    color: '#ffffff',
  },
  inputMethodButtons: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 15,
  },
  inputMethodButton: {
    backgroundColor: '#4a4a4a',
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
    minWidth: 120,
    borderWidth: 1,
    borderColor: '#6a6a6a',
  },
  inputMethodIcon: {
    fontSize: 24,
    marginBottom: 8,
  },
  inputMethodText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '500',
    textAlign: 'center',
  },
  inputMethodBeta: {
    color: '#a82828',
    fontSize: 10,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: 2,
  },
  inputMethodDivider: {
    alignItems: 'center',
    marginVertical: 10,
  },
  inputMethodDividerText: {
    color: '#c5c5c5',
    fontSize: 12,
    fontStyle: 'italic',
  },
  customInputSection: {
    backgroundColor: '#4a4a4a',
    padding: 15,
    borderRadius: 10,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#6a6a6a',
  },
  customInputTitle: {
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 15,
    textAlign: 'center',
    color: '#a82828',
  },
  customInputButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 15,
    gap: 15,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginTop: 20,
    marginBottom: 12,
    color: '#ffffff',
  },
  portionSizeSection: {
    marginBottom: 20,
  },
  servingSizeHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  numberInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  servingUnitLabel: {
    fontSize: 14,
    color: '#c5c5c5',
  },
  toggleButton: {
    backgroundColor: '#6a6a6a',
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#8a8a8a',
  },
  toggleButtonText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '500',
  },
});